### PR TITLE
Update README.md

### LINKED ISSUE #195: Installation instruction (in readme) does not work
### Description

Following the instructions:
```sh
curl https://forge.grails.org
```

gives error:
```sh
curl: (6) Could not resolve host: forge.grails.org
```

### PR DESCRIPTION
**Pull request by puneetbehl**
Fixes #195

### CODE REVIEW

**Comment by puneetbehl** [comment]
@matrei  please take a look

**Comment by matrei** [comment]
@puneetbehl Now the download succeeds (although that url is quite a mouthful :smile:)  and the application starts.
Maybe drop the `--request` parameter as GET is default and then use shortform for `--location` (`-L`) and `--output` (`-o`) to at least shorten it a bit?

**Comment by matrei** [comment]
Also the above says "If you prefer not to install an application to create **Micronaut** applications..."

**Comment by matrei** [comment]
Some more comments on the readme 😄

The swagger UI at https://grailsforge-latest-cjmq3uyfcq-uc.a.run.app/swagger/views/swagger-ui/index.html (link in the response from):
```console
curl https://grailsforge-latest-cjmq3uyfcq-uc.a.run.app
```
breaks with JS error: `Uncaught ReferenceError: SwaggerUIBundle is not defined`.

Also in the http response from that URL it shows how to create an app:
```console
To create a default application:

    $ curl https://grailsforge-latest-cjmq3uyfcq-uc.a.run.app/create/WEB/example -o example.zip
```
which is without the `--location` (`-L`) curl parameter. Then I wonder - is the `-L` necessary in the Readme example? If it is, it should also be added to the http response. Otherwise it should be removed from the Readme.

None of the links under the API and Documentation headings are working as they should.

Maybe the snapshots link should point to https://s01.oss.sonatype.org/content/repositories/snapshots/org/grails/forge/ instead of at the root?

There is no section #usingsnapshots in the Grails documentation:

> See the documentation in the [Grails Docs](https://docs.grails.org/latest/guide/index.html#usingsnapshots) for how to configure your build to use snapshots.

**Comment by matrei** [comment]
Also the app type is missing from the curl example in the readme, which now returns:
```json
{"message":"Not Found","_links":{"self":{"href":"/create/test1.zip","templated":false}},"_embedded":{"errors":[{"message":"Page Not Found"}]}}
```

**Comment by puneetbehl** [comment]
Thank you for your feedback, I have applied your suggestions. However, the swagger-ui and rapidoc views are not working on latest because unfortunately those aren't enable in the latest. This will be fixed with the next release. 

Also, can you please point me to the example `CURL` which is not working because the following `CURL` request is also fine:

```shell
curl https://grailsforge-latest-cjmq3uyfcq-uc.a.run.app/demo.zip -o demo.zip
```

**Comment by matrei** [comment]
Great!

I tried again tonight using your curl example and now I do get a proper starter zip. 👍 
I must have mistakenly had a `/create` without the `/{appType}` in the path: `curl https://grailsforge-latest-cjmq3uyfcq-uc.a.run.app/create/demo.zip -o demo.zip` which returns the response I showed earlier.

**Pull request merged**
