### PR TITLE
Remove versions from selenium in dependencies block as it is already …

### LINKED ISSUE #227: The Selenium version is unnecessarily declared multiple times
### Description

The selenium version is unnecessarily duplicated in the dependencies section, even though it is explicitly declared in the configurations section.

### Steps to Reproduce

1. Create a new Grails 6.1.0 app with `grails create-app g610app`
2. Open `build.gradle`

### Expected Behaviour

The selenium version only needs to be declared in the configurations block.

### Actual Behaviour

The selenium version is also declared 6 times in the dependencies block.

### PR DESCRIPTION
**Pull request by matrei**
…declared in the configurations block.

Fixes #227

### CODE REVIEW

**Comment by puneetbehl** [comment]
Where does the Selenium version comes from? I believe it is not part of the Grails BOM.

**Comment by matrei** [comment]
I think it is defined in the [/grails-forge-core/src/main/resources/pom.xml](https://github.com/grails/grails-forge/blob/a581c222/grails-forge-core/src/main/resources/pom.xml#L100-L104) file.
And then its injected here in [buildGradle.rocker.raw](https://github.com/grails/grails-forge/blob/a581c222/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw#L44-L55)

**Comment by puneetbehl** [comment]
Okay, I think we shouldn't remove it because I have only added the Gradle `configuration.all` block to force the version from transitive dependencies and we will remove it in the future once there is no such issue with transitives.

**Comment by matrei** [comment]
Ok, I understand. I just think it's bad DX to repeat the same version in so many places and saw an opportunity to remedy that now that it was defined in the configurations section.

**Comment by matrei** [comment]
Out of curiosity, why does the version of Selenium (and groovy-xml) need to be forced?

**Comment by puneetbehl** [comment]
I don't recall now but there were some incompatibility with transitives pulling in different versions, and groovy-xml default version is incompatible with Gradle.

**Comment by matrei** [comment]
> groovy-xml default version is incompatible with Gradle

Ok I see. I ask because I can remove it from a Grails 6.1.0 project without any errors. Maybe I haven't used the features that breaks.

And also it doesn't seem to pull in groovy-xml 3.0.13 anyway. Or am I missing something?

```console
~/test$ grails -V
Grails Version: 6.1.0
~/test$ grails create-webapp p610wa
| Application created at /home/mattias/test/p610wa
~/test$ cd p610wa
~/test/p610wa$ ./gradlew dI --dependency org.codehaus.groovy:groovy-xml --configuration compileClasspath

> Task :dependencyInsight
org.codehaus.groovy:groovy-xml:3.0.11
  Variant compile:
    | Attribute Name                 | Provided | Requested         |
    |--------------------------------|----------|-------------------|
    | org.gradle.status              | release  |                   |
    | org.gradle.category            | library  | library           |
    | org.gradle.libraryelements     | jar      | classes+resources |
    | org.gradle.usage               | java-api | java-api          |
    | org.gradle.dependency.bundling |          | external          |
    | org.gradle.jvm.environment     |          | standard-jvm      |
    | org.gradle.jvm.version         |          | 11                |
   Selection reasons:
      - Forced
      - Selected by rule

org.codehaus.groovy:groovy-xml:3.0.11
+--- org.grails:grails-bootstrap:6.1.0
|    +--- org.grails:grails-dependencies:6.1.0
|    |    \--- org.grails.plugins:scaffolding:5.0.1 (requested org.grails:grails-dependencies)
|    |         \--- compileClasspath (requested org.grails.plugins:scaffolding)
|    +--- org.grails:grails-datastore-gorm-support:8.0.2 (requested org.grails:grails-bootstrap:6.0.0)
|    |    +--- org.grails:grails-plugin-domain-class:6.1.0
|    |    |    \--- org.grails:grails-plugin-controllers:6.1.0
|    |    |         +--- org.grails:grails-plugin-interceptors:6.1.0
|    |    |         |    +--- compileClasspath (requested org.grails:grails-plugin-interceptors)
|    |    |         |    \--- org.grails:grails-dependencies:6.1.0 (*)
|    |    |         +--- org.grails:grails-plugin-rest:6.1.0
|    |    |         |    +--- compileClasspath (requested org.grails:grails-plugin-rest)
|    |    |         |    \--- org.grails:grails-dependencies:6.1.0 (*)
|    |    |         +--- org.grails:grails-plugin-url-mappings:6.1.0
|    |    |         |    +--- compileClasspath (requested org.grails:grails-plugin-url-mappings)
|    |    |         |    +--- org.grails:grails-dependencies:6.1.0 (*)
|    |    |         |    \--- org.grails:grails-plugin-interceptors:6.1.0 (*)
|    |    |         \--- org.grails.plugins:async:4.0.0 (requested org.grails:grails-plugin-controllers:4.0.0)
|    |    |              \--- org.grails:grails-dependencies:6.1.0 (*)
|    |    \--- org.grails.plugins:hibernate5:8.0.1 (requested org.grails:grails-datastore-gorm-support:8.0.1)
|    |         \--- compileClasspath (requested org.grails.plugins:hibernate5)
|    +--- org.grails:grails-core:6.1.0
|    |    +--- compileClasspath (requested org.grails:grails-core)
|    |    +--- org.grails:grails-logging:6.1.0
|    |    |    \--- compileClasspath (requested org.grails:grails-logging)
|    |    +--- org.grails:grails-plugin-databinding:6.1.0
|    |    |    +--- compileClasspath (requested org.grails:grails-plugin-databinding)
|    |    |    \--- org.grails:grails-dependencies:6.1.0 (*)
|    |    +--- org.grails:grails-plugin-services:6.1.0
|    |    |    +--- compileClasspath (requested org.grails:grails-plugin-services)
|    |    |    \--- org.grails:grails-dependencies:6.1.0 (*)
|    |    +--- org.grails:grails-plugin-controllers:6.1.0 (*)
|    |    +--- org.grails:grails-plugin-datasource:6.1.0
|    |    |    +--- org.grails:grails-plugin-services:6.1.0 (*)
|    |    |    \--- org.grails:grails-plugin-rest:6.1.0 (*)
|    |    +--- org.grails:grails-plugin-domain-class:6.1.0 (*)
|    |    +--- org.grails:grails-plugin-validation:6.1.0
|    |    |    +--- org.grails:grails-plugin-controllers:6.1.0 (*)
|    |    |    \--- org.grails:grails-plugin-domain-class:6.1.0 (*)
|    |    +--- org.grails:grails-web-common:6.1.0
|    |    |    +--- org.grails:grails-web-boot:6.1.0
|    |    |    |    +--- compileClasspath (requested org.grails:grails-web-boot)
|    |    |    |    \--- org.grails.plugins:scaffolding:5.0.1 (requested org.grails:grails-web-boot) (*)
|    |    |    +--- org.grails:grails-web:6.1.0
|    |    |    |    +--- org.grails:grails-plugin-databinding:6.1.0 (*)
|    |    |    |    +--- org.grails:grails-plugin-rest:6.1.0 (*)
|    |    |    |    +--- org.grails:grails-plugin-url-mappings:6.1.0 (*)
|    |    |    |    +--- org.grails:grails-plugin-controllers:6.1.0 (*)
|    |    |    |    +--- org.grails:grails-plugin-i18n:6.1.0
|    |    |    |    |    +--- compileClasspath (requested org.grails:grails-plugin-i18n)
|    |    |    |    |    \--- org.grails:grails-dependencies:6.1.0 (*)
|    |    |    |    +--- org.grails:grails-plugin-codecs:6.1.0
|    |    |    |    |    +--- org.grails.plugins:gsp:6.1.0 (requested org.grails:grails-plugin-codecs:6.0.0)
|    |    |    |    |    |    +--- compileClasspath (requested org.grails.plugins:gsp)
|    |    |    |    |    |    \--- org.grails:grails-dependencies:6.1.0 (*)
|    |    |    |    |    \--- org.grails.plugins:sitemesh2:6.1.0 (requested org.grails:grails-plugin-codecs:6.0.0)
|    |    |    |    |         \--- org.grails.plugins:gsp:6.1.0 (*)
|    |    |    |    +--- org.grails:grails-plugin-mimetypes:6.1.0
|    |    |    |    |    \--- org.grails:grails-plugin-controllers:6.1.0 (*)
|    |    |    |    \--- org.grails:grails-plugin-validation:6.1.0 (*)
|    |    |    +--- org.grails:grails-web-databinding:6.1.0
|    |    |    |    \--- org.grails:grails-web:6.1.0 (*)
|    |    |    +--- org.grails:grails-web-fileupload:6.1.0
|    |    |    |    \--- org.grails:grails-web:6.1.0 (*)
|    |    |    +--- org.grails:grails-web-mvc:6.1.0
|    |    |    |    \--- org.grails:grails-web:6.1.0 (*)
|    |    |    +--- org.grails:grails-web-url-mappings:6.1.0
|    |    |    |    +--- org.grails:grails-web:6.1.0 (*)
|    |    |    |    \--- org.grails:grails-web-mvc:6.1.0 (*)
|    |    |    +--- org.grails:grails-web-sitemesh:6.1.0 (requested org.grails:grails-web-common:6.0.0)
|    |    |    |    +--- org.grails:grails-plugin-controllers:6.1.0 (*)
|    |    |    |    \--- org.grails.plugins:sitemesh2:6.1.0 (*)
|    |    |    +--- org.grails:grails-web-jsp:6.1.0 (requested org.grails:grails-web-common:6.0.0)
|    |    |    |    \--- org.grails:grails-web-gsp-taglib:6.1.0
|    |    |    |         \--- org.grails.plugins:gsp:6.1.0 (*)
|    |    |    \--- org.grails:grails-web-gsp:6.1.0 (requested org.grails:grails-web-common:6.0.0)
|    |    |         +--- org.grails:grails-web:6.1.0 (*)
|    |    |         \--- org.grails:grails-web-jsp:6.1.0 (*)
|    |    +--- org.grails:grails-datastore-gorm-support:8.0.2 (requested org.grails:grails-core:6.0.0) (*)
|    |    +--- org.grails:grails-encoder:6.1.0
|    |    |    +--- org.grails:grails-plugin-codecs:6.1.0 (*)
|    |    |    \--- org.grails:grails-web-common:6.1.0 (*)
|    |    \--- org.grails.plugins:events:4.0.0 (requested org.grails:grails-core:4.0.0)
|    |         \--- org.grails.plugins:async:4.0.0 (*)
|    \--- org.grails:grails-spring:6.1.0
|         +--- org.grails:grails-plugin-domain-class:6.1.0 (*)
|         \--- org.grails:grails-core:6.1.0 (*)
\--- org.grails:grails-databinding:6.1.0
     +--- org.grails:grails-web-databinding:6.1.0 (*)
     \--- org.grails:grails-web-common:6.1.0 (*)

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 3s
2 actionable tasks: 2 executed
```

**Comment by puneetbehl** [comment]
Please check here https://docs.gradle.org/7.6/userguide/upgrading_version_7.html#changes_7.6

**Comment by matrei** [comment]
I don't seem to be able to find any information about groovy version incompatibility at the provided link.

https://docs.gradle.org/7.6/userguide/compatibility.html#groovy
does not mention it either.

**Pull request closed without merging**
